steps:
  - id: 'create-data-agent' 
    name: 'python:3.11-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements.txt
        python data_agent_from_agent_card.py --project_id=$PROJECT_ID --file_path=agent_card.json

options:
  logging: CLOUD_LOGGING_ONLY